In [1]:
# importing
import pandas
from bokeh.plotting import figure, output_file, show

In [2]:
# create object of figure
p=figure(plot_width=500,plot_height=400, tools='pan')

# giving properties to figure object
p.title.text="Cool Data"
p.title.text_color="Gray"
p.title.text_font="times"
p.title.text_font_style="bold"
p.xaxis.minor_tick_line_color=None
p.yaxis.minor_tick_line_color=None
p.xaxis.axis_label="Date"
p.yaxis.axis_label="Intensity" 

# create line
p.line([1,2,3],[4,5,6])

output_file("graph.html")
show(p)

In [3]:
# importing 
import pandas
from bokeh.plotting import figure, output_file, show

# load data from excel file
df=pandas.read_excel("http://pythonhow.com/data/verlegenhuken.xlsx",sheet_name=0)
df["Temperature"]=df["Temperature"]/10
df["Pressure"]=df["Pressure"]/10
 
# create object of figure
p=figure(plot_width=500,plot_height=400,tools='pan')
 
p.title.text="Temperature and Air Pressure"
p.title.text_color="Gray"
p.title.text_font="arial"
p.title.text_font_style="bold"
p.xaxis.minor_tick_line_color=None
p.yaxis.minor_tick_line_color=None
p.xaxis.axis_label="Temperature (°C)"
p.yaxis.axis_label="Pressure (hPa)"    
 
p.circle(df["Temperature"],df["Pressure"],size=0.5)
output_file("Weather.html")
show(p)

In [4]:
df

       Year  Month  Day  Hour  Temperature  Pressure
0      2010     10    6     3         -3.0     998.4
1      2010     10    6     9         -2.8     999.2
2      2010     10    6    10         -2.4     998.7
3      2010     10    6    11         -1.9     998.7
4      2010     10    6    12         -1.9     998.5
...     ...    ...  ...   ...          ...       ...
33097  2014     12   30     9        -11.6     989.6
33098  2014     12   30    12        -10.3     986.6
33099  2014     12   30    15         -9.7     982.6
33100  2014     12   30    18         -9.3     982.9
33101  2014     12   30    21         -8.6     980.4

[33102 rows x 6 columns]

In [5]:
from bokeh.plotting import figure, output_file, show

p = figure(plot_width=500, plot_height=400, tools = 'pan, reset')

p.title.text = "Earthquakes"
p.title.text_color = "Orange"
p.title.text_font = "times"
p.title.text_font_style = "italic"
p.yaxis.minor_tick_line_color = "Yellow"
p.xaxis.axis_label = "Times"
p.yaxis.axis_label = "Value"

p.circle([1,2,3,4,5], [5,6,5,5,3], size = [i*2 for i in [8,12,14,15,20]], color="red", alpha=0.5)
output_file("Scatter_plotting.html")
show(p)